# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56d73ad4728ba62600ad0bc1bb9821a7261a41502267f0d617a5892eacc10cc7dd3ca7273be51e40ef9553a3ce00bd617c7f2df20aa07eff7381337875dffcbb

test:
  secret_key_base: 1f2500aef4b7f8a2e76482e3e85382b4ea5df6ff7aa2852bcebba1631d92d34d5c6e16f8394f3b603a58db0192b9655c8e9ef511d9dc5ff62984dab84034976f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
